### ISSUE TITLE
Possible operators

### ISSUE THREAD

**Issue by hesa** [hesa/foss-licenses#107]
Is there an interpretation for the following: `+` `/`

**Comment by silverhook** [comment]
Context?

**Comment by hesa** [comment]
Example: "MIT + GPLv2"

What does + refer to? AND or OR?

My guess would be OR, but that the effect on such an assumption is severe.

**Comment by hesa** [comment]
Probably "+" can be treated as "AND" - it will not be create false positives at least. I would say let's stick with not allowing "+" as an operator.

**Comment by hesa** [comment]
there seems to be no de-facto standard for `+` etc, so not adding anything
